"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^_mm@qbj)t7)ac(_0x==7gj@0h78@!nswtc!4l%1i=xzw!6859"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core", 
    "users",
    'rest_framework',
    'rest_framework.authtoken',    
    'corsheaders',
    'jobs',
    'models_history',
    "storages"  
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Spostato più in alto
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8080",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database - CONNESSIONE AL DATABASE POSTGRESQL SUPABASE
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.muvnrrcpfsqimwzkjzpz',
        'PASSWORD': '**Tfd4Pu?a*yAi!',
        'HOST': 'aws-0-eu-west-3.pooler.supabase.com',
        'PORT': '6543',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CELERY CONFIG - PER TASK ASINCRONI
CELERY_BROKER_URL = "redis://default:CItpjCfWaaRXFjLClIEkXeKrfVdAPWKM@trolley.proxy.rlwy.net:31412"
CELERY_RESULT_BACKEND = "redis://default:CItpjCfWaaRXFjLClIEkXeKrfVdAPWKM@trolley.proxy.rlwy.net:31412"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# =====================================================
# SUPABASE STORAGE CONFIGURATION - CONFIGURAZIONE CORRETTA
# =====================================================

# Credenziali S3 per Supabase Storage (LE TUE CREDENZIALI CORRETTE)
AWS_ACCESS_KEY_ID = "608260a0a7cbc9e29a5b4211ed38c3a4"
AWS_SECRET_ACCESS_KEY = "c0ad804d9b224b13e39b68610e06b3bd99c3b787426d38f07f4a0ab615eba20b"

# Configurazione endpoint e bucket
AWS_S3_ENDPOINT_URL = "https://muvnrrcpfsqimwzkjzpz.supabase.co/storage/v1/s3"
AWS_STORAGE_BUCKET_NAME = "project-files"
AWS_S3_REGION_NAME = "us-east-1"  # Standard per Supabase
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_LOCATION = ""  # Cartella root nel bucket

# URL pubblico per servire i file
AWS_S3_CUSTOM_DOMAIN = f"muvnrrcpfsqimwzkjzpz.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}"

# Configurazione per bucket pubblico
AWS_DEFAULT_ACL = 'public-read'  # Files pubblicamente leggibili
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # Cache per 24 ore
}
AWS_S3_FILE_OVERWRITE = False  # Non sovrascrivere file esistenti
AWS_QUERYSTRING_AUTH = False  # Non aggiungere parametri di auth agli URL pubblici
AWS_S3_VERIFY = True  # Verifica SSL

# Configurazione STORAGES (Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# settings.py
SUPABASE_URL = "https://muvnrrcpfsqimwzkjzpz.supabase.co"  # Sostituisci con il tuo URL
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dm5ycmNwZnNxaW13emtqenB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjYyODcsImV4cCI6MjA2NTMwMjI4N30.kxJxG8WQ-COxeUd4nlYC5D2pVVjTuD44k0MOAPXmrRc"  # Sostituisci con la tua chiave


# URL per servire i media files
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

CELERY_TASK_ALWAYS_EAGER = True
