# netlify.toml - File di configurazione Netlify

[build]
  # Comando per build del progetto
  command = "npm run build"
  
  # Directory di output (dove Vite mette i file built)
  publish = "dist"

[build.environment]
  # Versione Node.js da usare
  NODE_VERSION = "18"
  
  # Variabili environment per il build
  VITE_API_URL = "https://thesisproject-production.up.railway.app"

# Redirect per Single Page Application (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers per sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache per assets statici
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"