
services:
  celery-worker:
    image: matteopostiferi/hunyuan3d-2gp-app:latest
    working_dir: /app
    command: celery -A backend worker --loglevel=info --concurrency=1
    environment:
      - CELERY_BROKER_URL=redis://default:CItpjCfWaaRXFjLClIEkXeKrfVdAPWKM@trolley.proxy.rlwy.net:31412/0
      - CELERY_RESULT_BACKEND=redis://default:CItpjCfWaaRXFjLClIEkXeKrfVdAPWKM@trolley.proxy.rlwy.net:31412/0
      - CELERY_ACCEPT_CONTENT=json
      - CELERY_TASK_SERIALIZER=json
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./:/app
    restart: unless-stopped

  flower:
    image: matteopostiferi/hunyuan3d-2gp-app:latest
    working_dir: /app
    command: celery -A backend flower --port=5555 --broker=redis://default:CItpjCfWaaRXFjLClIEkXeKrfVdAPWKM@trolley.proxy.rlwy.net:31412/0
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://default:CItpjCfWaaRXFjLClIEkXeKrfVdAPWKM@trolley.proxy.rlwy.net:31412/0
      - CELERY_RESULT_BACKEND=redis://default:CItpjCfWaaRXFjLClIEkXeKrfVdAPWKM@trolley.proxy.rlwy.net:31412/0
      - FLOWER_BASIC_AUTH=admin:password123
    depends_on:
      - celery-worker
    restart: unless-stopped
