version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - celery-network

  web:
    image: matteopostiferi/hunyuan3d-2gp-app:latest
    working_dir: /workspace/ThesisProject/3d-webgen/backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=<la-tua-stringa-DB>
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/workspace/ThesisProject/3d-webgen:/workspace/Hunyuan3D-2GP
    volumes:
      - ./backend:/workspace/ThesisProject/3d-webgen/backend
      - ./core:/workspace/ThesisProject/3d-webgen/core
    networks:
      - celery-network

  celery-worker:
    image: matteopostiferi/hunyuan3d-2gp-app:latest
    working_dir: /workspace/ThesisProject/3d-webgen/backend
    command: celery -A backend.celery worker --loglevel=info --concurrency=1
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/workspace/ThesisProject/3d-webgen:/workspace/Hunyuan3D-2GP
    volumes:
      - ./backend:/workspace/ThesisProject/3d-webgen/backend
      - ./core:/workspace/ThesisProject/3d-webgen/core
      - ./output:/workspace/output
      - ./cache:/workspace/cache
    restart: unless-stopped
    networks:
      - celery-network

  flower:
    image: matteopostiferi/hunyuan3d-2gp-app:latest
    working_dir: /workspace/ThesisProject/3d-webgen/backend
    command: celery -A backend.celery flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend:/workspace/ThesisProject/3d-webgen/backend
      - ./core:/workspace/ThesisProject/3d-webgen/core
    networks:
      - celery-network

volumes:
  redis_data:

networks:
  celery-network:
    driver: bridge
